services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 120s

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    image: finn-loan-analysis-backend  # Match the built image name
    ports:
      - "8000:8000"
    volumes:
      - ./Back/Data:/app/Data
      - ./Back/PDF Loans:/app/PDF Loans
      - ./Back/loans_vector.db:/app/loans_vector.db
      - ./Back/loan_analysis.db:/app/loan_analysis.db
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    image: finn-loan-analysis-frontend  # Match the built image name
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    depends_on:
      - prometheus

  jenkins:
    build: ./jenkins  # Use custom Dockerfile
    ports:
      - "9190:8080"  
      - "9191:50000"  
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/scripts:/var/jenkins_scripts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    user: root
    privileged: true

volumes:
  ollama_data:
  prometheus_data:
  grafana_data:
  jenkins_data: